# Working with data

In [1]:
import numpy as np
import pandas as pd

## CSV files in Pandas
Download the iris dataset through the terminal. Nake sure it is in the same folder as this notebook
curl -L bit.ly/sparta_iris > iris.csv

In [33]:
# using read_csv
iris = pd.read_csv("iris.csv")
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [34]:
# Use .head(), what does it do? It takes the first 5 rows of tables when not specified.
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
 # Write a df to a new csv
df = pd.DataFrame([["Matt", "25"], ["Steve", "20"]], columns=["name", "age"])
df.to_csv("out.csv", index=False)

In [9]:
df_read = pd.read_csv("out.csv")
df_read

    name  age
0   Matt   25
1  Steve   20

In [23]:
# Use .groupby, what does it do? finds duplicate rows in the selected column, in this example "Persons" and groups them with a mean of their age.
df2 = pd.DataFrame(
    {
        "Persons": ["Steve", "Bill", "Steve", "Bill"],
        "Age": [30, 40, 20, 35],
    }
)
df2.groupby(["Persons"]).mean()

          Age
Persons
Bill     37.5
Steve    25.0

In [38]:
iris.groupby(["sepal_length"]).sum()

,sepal_width,petal_length,petal_width,species
sepal_length,,,,
4.3,3.0,1.1,0.1,setosa
4.4,9.1,4.0,0.6,setosasetosasetosa
4.5,2.3,1.3,0.3,setosa
4.6,13.3,5.3,0.9,setosasetosasetosasetosa
4.7,6.4,2.9,0.4,setosasetosa
4.8,15.9,7.9,1.0,setosasetosasetosasetosasetosa
4.9,17.2,13.7,3.2,setosasetosasetosasetosaversicolorvirginica
5.0,31.2,18.4,4.3,setosasetosasetosasetosasetosasetosasetosaseto...
5.1,31.3,15.5,3.6,setosasetosasetosasetosasetosasetosasetosaseto...
5.2,13.7,8.3,1.9,setosasetosasetosaversicolor
5.3,3.7,1.5,0.2,setosa
5.4,21.3,12.2,3.1,setosasetosasetosasetosasetosaversicolor
5.5,19.9,22.6,6.3,setosasetosaversicolorversicolorversicolorvers...
5.6,16.9,25.2,8.5,versicolorversicolorversicolorversicolorversic...
5.7,24.8,28.7,8.8,setosasetosaversicolorversicolorversicolorvers...
5.8,20.2,28.5,9.8,setosaversicolorversicolorversicolorvirginicav...
5.9,9.2,14.1,5.1,versicolorversicolorvirginica
6.0,16.4,27.9,9.0,versicolorversicolorversicolorversicolorvirgin...
6.1,17.1,28.5,8.5,versicolorversicolorversicolorversicolorvirgin...
6.2,11.3,19.0,6.9,versicolorversicolorvirginicavirginica
6.3,25.7,46.2,16.3,versicolorversicolorversicolorvirginicavirgini...
6.4,20.7,36.1,13.1,versicolorversicolorvirginicavirginicavirginic...
6.5,15.0,26.2,9.5,versicolorvirginicavirginicavirginicavirginica
6.6,5.9,9.0,2.7,versicolorversicolor
6.7,24.4,42.1,15.7,versicolorversicolorversicolorvirginicavirgini...
6.8,9.0,16.2,5.8,versicolorvirginicavirginica
6.9,12.5,21.1,8.2,versicolorvirginicavirginicavirginica
7.0,3.2,4.7,1.4,versicolor
7.1,3.0,5.9,2.1,virginica
7.2,9.8,17.9,5.9,virginicavirginicavirginica
7.3,2.9,6.3,1.8,virginica
7.4,2.8,6.1,1.9,virginica
7.6,3.0,6.6,2.1,virginica
7.7,12.2,26.4,8.8,virginicavirginicavirginicavirginica
7.9,3.8,6.4,2.0,virginica

In [40]:
# Iterate through the data (removing header)
pd.read_csv("iris.csv", header=None)

                0            1             2            3          4
0    sepal_length  sepal_width  petal_length  petal_width    species
1             5.1          3.5           1.4          0.2     setosa
2             4.9          3.0           1.4          0.2     setosa
3             4.7          3.2           1.3          0.2     setosa
4             4.6          3.1           1.5          0.2     setosa
..            ...          ...           ...          ...        ...
146           6.7          3.0           5.2          2.3  virginica
147           6.3          2.5           5.0          1.9  virginica
148           6.5          3.0           5.2          2.0  virginica
149           6.2          3.4           5.4          2.3  virginica
150           5.9          3.0           5.1          1.8  virginica

[151 rows x 5 columns]

In [43]:
pd.read_csv("iris.csv", index_col="sepal_length")

              sepal_width  petal_length  petal_width    species
sepal_length
5.1                   3.5           1.4          0.2     setosa
4.9                   3.0           1.4          0.2     setosa
4.7                   3.2           1.3          0.2     setosa
4.6                   3.1           1.5          0.2     setosa
5.0                   3.6           1.4          0.2     setosa
...                   ...           ...          ...        ...
6.7                   3.0           5.2          2.3  virginica
6.3                   2.5           5.0          1.9  virginica
6.5                   3.0           5.2          2.0  virginica
6.2                   3.4           5.4          2.3  virginica
5.9                   3.0           5.1          1.8  virginica

[150 rows x 4 columns]

In [45]:
# Use .describe() on the data
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## Iris dataset

In [56]:
# Add a rank column, ranking petal length in asc order
iris.rank(ascending = True)

     sepal_length  sepal_width  petal_length  petal_width  species
0            37.0        129.5          17.5         20.5     25.5
1            19.5         70.5          17.5         20.5     25.5
2            10.5        102.0           8.0         20.5     25.5
3             7.5         89.5          30.5         20.5     25.5
4            27.5        134.0          17.5         20.5     25.5
..            ...          ...           ...          ...      ...
145         126.5         70.5         117.5        140.5    125.5
146         104.0         15.5         106.5        119.0    125.5
147         118.0         70.5         117.5        124.5    125.5
148          97.5        120.5         121.5        140.5    125.5
149          82.0         70.5         112.5        110.5    125.5

[150 rows x 5 columns]

In [70]:
# Find the mean of each column for each species
iris_mean = iris.groupby("species").mean()
iris_mean

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [72]:
# Create a new df for each species separately (3 total)
# df = iris.groupby("species")
# df

In [74]:
#Create 2 final df, one for sepal info and one for petal info (with data from all three species in each)

## JSON files and Pandas

In [76]:
# Load data from this link https://www.kaggle.com/rtatman/iris-dataset-json-version
import kagglehub

# Download latest version
path = kagglehub.dataset_download("rtatman/iris-dataset-json-version")

print("Path to dataset files:", path)

ModuleNotFoundError: No module named 'kagglehub'

In [78]:
# Use .head() to verify the importing

## Merging

In [80]:
# Find a way to merge your sepal_info and petal_info dataframes

In [82]:
# Drop repeated columns from your merged df

## Concatenation

In [85]:
# Use .concat() on your main df. What does it do?

## Reshaping

Install the library "Seaborn"

Import it to your notebook

In [87]:
# Load the flights dataset "flights = sns.load_dataset('flights')"

In [89]:
# Check it out with .head()

In [91]:
# use. pivot() to pivot the data to be long format

In [93]:
# Try out .stack(), what does it do?

In [95]:
# Try .unstack(), what does it do?

In [97]:
# Try crosstab(), what does it do?

## Aggregations

- Load the titanic dataset from Seaborn

- Explore the dataset with Pandas

- Clean the dataset --> Duplicates, Missing Values etc.

In [112]:
# Clean:
titanic = pd.read_csv("titanic.csv")
titanic.dropna()
titanic.drop_duplicates(inplace=True)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [127]:
# Find the average fare and age for each class
titanic.groupby('fare')['survived'].mean().sort_values()

fare
4.0125      0.0
5.0000      0.0
6.2375      0.0
6.4375      0.0
6.4958      0.0
           ...
134.5000    1.0
120.0000    1.0
211.3375    1.0
262.3750    1.0
512.3292    1.0
Name: survived, Length: 248, dtype: float64

In [101]:
# Add a new column showing fare as a percentage of total

In [117]:
# How many survivors were female, compared to male
titanic.groupby('sex')['survived'].mean()

sex
female    0.740614
male      0.215886
Name: survived, dtype: float64

In [104]:
# What other interesting insights can you find?